### ISSUE TITLE
Authoring Tool add component bug

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#2131]
### Description

1. Log in as a teacher
1. Open a project in the authoring tool
1. Enter a step
1. Add a component to the step
1. Click the checkbox for the component
1. Click the delete button and click OK. Right after you click OK, quickly click the "Add Component" button.
1. You will see the component types that you can choose but the arrows to choose where to insert the component will not be shown.

This is what it will look like when the problem occurs
![Screen Shot 2019-11-20 at 6 11 41 PM](https://user-images.githubusercontent.com/1036509/69286521-7d7a9280-0bc1-11ea-9d81-3bc3b2ce5d7f.png)

This is what it should look like
![Screen Shot 2019-11-20 at 6 11 54 PM](https://user-images.githubusercontent.com/1036509/69286514-78b5de80-0bc1-11ea-8263-8930240ce120.png)

**Comment by LoserNoOne** [comment]
I found that this error might be caused by this line. Do we still need this feature to let the author see the changes they just made?

https://github.com/WISE-Community/WISE/blob/issue-2141-refactor-gradeworkcontroller-with-authentication/src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js#L2850

**Comment by geoffreykwan** [comment]
@LoserNoOne You can remove that feature if it fixes the bug. That feature isn't really that important.
