### ISSUE TITLE
Embedded Component Sizing issue in Firefox

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#600]
Setup: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

The embedded component has scroll bars. I'm not sure why we're seeing 2. Instead, it should show the entire window and not require the scrollbar. It works fine on Chrome.
<img width="1552" alt="screen shot 2016-04-05 at 4 23 16 pm" src="https://cloud.githubusercontent.com/assets/119416/14301228/ef99eda6-fb4a-11e5-9755-5def8cce1fcd.png">

**Comment by breity** [comment]
Yeah, I think this is because Firefox just sets a default height on an iframe if one isn't specified.  You'll probably eventually see double scrollbars on Chrome if you make the screen height smaller.

1a6e95b adds support for automatically resizing the application iframe based on the embedded application's content and should fix this (as long as the embedded component includes the required js file).  I'll document the requirement for embedded component authors in the wiki.
