### ISSUE TITLE
Close notebook item by clicking outside the editing notebook box

### ISSUE THREAD

**Issue by alvenw** [WISE-Community/WISE#644]
Make it possible to close the notebook item when clicking outside the editing box

**Comment by hirokiterashima** [comment]
@breity is this still the behavior that we want? I'm now thinking that it'd be ok to have students click on the "cancel" button (or hit the esc key) to close the box. They might mis-click outside of the box and lose their work, which would be bad. What do you think?

**Comment by breity** [comment]
Yeah I think this might not be the best behavior.  We don't want them to inadvertently lose a note draft. Cancel or esc are probably fine for closing the dialog.  We could switch the button text to "Close" for notes that have already been created, since "Cancel" isn't the right terminology if a student is just trying to view note contents.

**Comment by hirokiterashima** [comment]
closing. no longer needed.
