### ISSUE TITLE
Previously reported security vulnerability, status?

### ISSUE THREAD

**Issue by tenablesecurity** [WISE-Community/WISE#659]
WISE team,

I reported a vulnerability to you via your contact form on 2016-03-04 and Hiroki Terashima confirmed receipt of it [1]. I haven't heard back regarding this report, but noticed two versions have been released since (neither appear to mention fixing the issue). I still don't have an email contact for proper follow-up, so opening this ticket to hopefully figure out the status of this.

Brian

[1] https://groups.google.com/forum/#!topic/wise-dev/Lr6WF_oznP0

**Comment by hirokiterashima** [comment]
Hi Brian @tenablesecurity, thanks for bringing it to our attention again. We've read your report and we will probably handle it by removing apache common-upload and use Spring's fileupload instead.

We have an issue (#435) for this already, so you can follow that to keep informed of our progress. Since WISE is open-source, you can also make the fix and send a PR if you have time/expertise.

**Comment by tenablesecurity** [comment]
Excellent, I subscribed to that ticket, thank you. Tenable will not be able to submit a PR unfortunately.
