### ISSUE TITLE
AT: separate views into tabs

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#732]
(For 5.3.2)

Put simple, preview, and advanced authoring into their own tabs, for each component.

This will reduce the amount of scrolling that the author has to do.

**Comment by geoffreykwan** [comment]
Instead of a tab for advanced authoring, we're trying a show/hide button for the advanced authoring textarea. We'll keep the preview where it is for now and see how we like it now that the advanced authoring textarea is no longer taking up vertical space.
https://github.com/WISE-Community/WISE/commit/fc59037485b4a1961a3e376efb790c9da869829f
