### ISSUE TITLE
The expand arrows in the grading tool in the grade by step view should show some informative information about what is hidden

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#792]
Right now it's a little confusing as to what is hidden. It's also confusing because some things expand and show an empty space.

![grading_tool_drop_downs](https://cloud.githubusercontent.com/assets/1036509/23928727/b8d0a722-08de-11e7-8ae4-805361004b27.png)

**Comment by breity** [comment]
Yeah I had labels on those initially.  I thought it looked a little clunky but I can add them back.  I agree they can be confusing.  Figuring out terminology teachers will recognize is the tough part.  I was just using "Hide section" and "Show section".  So maybe that could work.

The reason some sections are empty is because the grading view for those component types are broken (or are set to not show anything).  Once we fix those, there shouldn't be any empty sections.  I have this on my list to fix.

**Comment by breity** [comment]
We replaced the expand arrows with a component filter at the top of the step grading display.
